#!/usr/bin/env python

import rospy
from sensor_msgs.msg import PointCloud2


def callback(msg):
    rospy.logwarn("Received message")
    rospy.loginfo(f"Delay: {round((rospy.Time.now() - msg.header.stamp).to_sec(), 2)} s.")


if __name__ == "__main__":
    rospy.init_node("clouds_delay", anonymous=True, log_level=rospy.DEBUG)
    rospy.Subscriber("/points", PointCloud2, callback)
    # rospy.Subscriber("/points_filtered", PointCloud2, callback)
    rospy.spin()
